repos:
  - repo: https://github.com/nholuongut/terraform-pre-commit
    rev: v1.77.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: tfupdate

  - repo: https://github.com/nholuongut/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
